import os, re, uuid
from datetime import datetime
from state import PipelineState
from git_ops import get_branch_sha, create_branch, upsert_file, open_pull_request, GitHubError

def _slugify(text): return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:40]

def _plan_snapshot(scenarios):
    lines = ["### Plan snapshot (from Planner)", ""]
    for s in scenarios:
        lines.append(f"- `{s['id']}` [{s['layer']}/{s['role']}/{s['platform']}/{s['priority']}] {s['description']}")
    return "\n".join(lines)

def publisher_node(state: PipelineState) -> PipelineState:
    owner, repo, token = os.getenv("GITHUB_OWNER"), os.getenv("GITHUB_REPO"), os.getenv("GITHUB_TOKEN")
    base_branch = os.getenv("GITHUB_BASE_BRANCH", "main")

    if not state.get("validation_passed"):
        return {**state, "publish_result": {"status": "skipped", "reason": "Creator's output failed validation"}}
    if not (owner and repo and token):
        return {**state, "publish_result": {"status": "skipped",
            "reason": "GITHUB_OWNER/REPO/TOKEN not set -- feature written locally at " + state["feature_path"]}}

    slug = _slugify(state["jira_ticket"][:40])
    unique_id = f"{datetime.now().strftime('%Y%m%d%H%M%S')}-{uuid.uuid4().hex[:6]}"
    branch_name = f"feature/{slug}-{unique_id}"
    repo_path = "karate/features/generated/" + os.path.basename(state["feature_path"])

    try:
        base_sha = get_branch_sha(owner, repo, base_branch, token)
        create_branch(owner, repo, branch_name, base_sha, token)
        upsert_file(owner, repo, branch_name, repo_path, state["feature_text"],
            message=f"Add generated Karate feature: {slug}", token=token)
        pr_body = f"Auto-generated by the Creator agent.\n\n**User story:**\n{state['jira_ticket']}\n\n{_plan_snapshot(state.get('scenarios', []))}"
        pr_url = open_pull_request(owner, repo, branch_name, base_branch, title=f"[generated] {slug}", body=pr_body, token=token)
        return {**state, "publish_result": {"status": "opened", "branch": branch_name, "pr_url": pr_url}}
    except GitHubError as e:
        return {**state, "publish_result": {"status": "failed", "reason": str(e)}}